openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/auth/login:
    post:
      summary: ''
      operationId: postApiAuthLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: magnam
                password:
                  type: string
                  description: ''
                  example: quia
              required:
                - email
                - password
      security: []
  /api/crud/user:
    get:
      summary: 'GET. List Data'
      operationId: gETListData
      description: ''
      parameters:
        -
          in: query
          name: search
          description: 'For searching data.'
          example: et
          required: false
          schema:
            type: string
            description: 'For searching data.'
            example: et
        -
          in: query
          name: filter
          description: 'For filtering data.'
          example: aut
          required: false
          schema:
            type: string
            description: 'For filtering data.'
            example: aut
        -
          in: query
          name: sort
          description: 'For sorting data.'
          example: aut
          required: false
          schema:
            type: string
            description: 'For sorting data.'
            example: aut
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: 'POST. Create Data'
      operationId: pOSTCreateData
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/crud/user/scope/{scope}':
    get:
      summary: 'GET. Scope'
      operationId: gETScope
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: scope
        description: 'The scope.'
        example: s
        required: true
        schema:
          type: string
  /api/crud/user/spec:
    get:
      summary: 'GET. Spec'
      operationId: gETSpec
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/crud/user/{id}':
    get:
      summary: 'GET. Detail Data'
      operationId: gETDetailData
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: 'POST. PUT. Update Data'
      operationId: pOSTPUTUpdateData
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    delete:
      summary: 'DELETE. Data'
      operationId: dELETEData
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the user.'
        example: 1
        required: true
        schema:
          type: integer
  /api/crud/user/bulk:
    post:
      summary: 'POST. Bulk Data'
      operationId: pOSTBulkData
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/crud/permissions:
    get:
      summary: 'GET. List Data'
      operationId: gETListData
      description: ''
      parameters:
        -
          in: query
          name: search
          description: 'For searching data.'
          example: vero
          required: false
          schema:
            type: string
            description: 'For searching data.'
            example: vero
        -
          in: query
          name: filter
          description: 'For filtering data.'
          example: corrupti
          required: false
          schema:
            type: string
            description: 'For filtering data.'
            example: corrupti
        -
          in: query
          name: sort
          description: 'For sorting data.'
          example: temporibus
          required: false
          schema:
            type: string
            description: 'For sorting data.'
            example: temporibus
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: 'POST. Create Data'
      operationId: pOSTCreateData
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/crud/permissions/scope/{scope}':
    get:
      summary: 'GET. Scope'
      operationId: gETScope
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: scope
        description: 'The scope.'
        example: Wz
        required: true
        schema:
          type: string
  /api/crud/permissions/spec:
    get:
      summary: 'GET. Spec'
      operationId: gETSpec
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/crud/permissions/{id}':
    get:
      summary: 'GET. Detail Data'
      operationId: gETDetailData
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: 'POST. PUT. Update Data'
      operationId: pOSTPUTUpdateData
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    delete:
      summary: 'DELETE. Data'
      operationId: dELETEData
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the permission.'
        example: '333'
        required: true
        schema:
          type: string
  /api/crud/permissions/bulk:
    post:
      summary: 'POST. Bulk Data'
      operationId: pOSTBulkData
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/crud/role:
    get:
      summary: 'GET. List Data'
      operationId: gETListData
      description: ''
      parameters:
        -
          in: query
          name: search
          description: 'For searching data.'
          example: cum
          required: false
          schema:
            type: string
            description: 'For searching data.'
            example: cum
        -
          in: query
          name: filter
          description: 'For filtering data.'
          example: hic
          required: false
          schema:
            type: string
            description: 'For filtering data.'
            example: hic
        -
          in: query
          name: sort
          description: 'For sorting data.'
          example: qui
          required: false
          schema:
            type: string
            description: 'For sorting data.'
            example: qui
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: 'POST. Create Data'
      operationId: pOSTCreateData
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/crud/role/scope/{scope}':
    get:
      summary: 'GET. Scope'
      operationId: gETScope
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: scope
        description: 'The scope.'
        example: '95'
        required: true
        schema:
          type: string
  /api/crud/role/spec:
    get:
      summary: 'GET. Spec'
      operationId: gETSpec
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/crud/role/{id}':
    get:
      summary: 'GET. Detail Data'
      operationId: gETDetailData
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: 'POST. PUT. Update Data'
      operationId: pOSTPUTUpdateData
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    delete:
      summary: 'DELETE. Data'
      operationId: dELETEData
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the role.'
        example: '7441834'
        required: true
        schema:
          type: string
  /api/crud/role/bulk:
    post:
      summary: 'POST. Bulk Data'
      operationId: pOSTBulkData
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/auth/info:
    get:
      summary: ''
      operationId: getApiAuthInfo
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/auth/logout:
    post:
      summary: ''
      operationId: postApiAuthLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
