<?php

namespace App\Services\Pegawai;

use _PHPStan_c6b09fbdf\Nette\Schema\ValidationException;
use App\Models\KasbonBulanan;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator;
use Laravolt\Crud\Contracts\StoreRequestContract;
use Laravolt\Crud\CrudModel;
use Laravolt\Crud\CrudService;
use Laravolt\Crud\Sys\ActivityLog\AkActivityLog;

class KasbonBulananService extends CrudService
{

    public function beforeCreateHook(FormRequest|StoreRequestContract $requestContract)
    {
        $alreadyExsist = KasbonBulanan::where("bulan", $requestContract->bulan)
            ->where("tahun", $requestContract->tahun)
            ->where("perusahaan_id", $requestContract->perusahaan_id)
            ->where("cabang_id", $requestContract->cabang_id)->first();
        if ($alreadyExsist) {
            throw \Illuminate\Validation\ValidationException::withMessages(['bulan' => 'Sudah Memiliki Kasbon di periode tersebut']);
        }
        $requestContract->merge(['status' => "NEW"]);
        return parent::beforeCreateHook($requestContract); // TODO: Change the autogenerated stub
    }

    public function delete(mixed $model): ?bool
    {
        if($model->status != "NEW") {
            throw \Illuminate\Validation\ValidationException::withMessages(['status' => 'Data Dengan Status ' . $model->status . ' Tidak bisa di hapus']);
        }
        return  parent::delete($model);
    }

}
